name: Deploy Lambda

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy Lambda
        run: yarn serverless deploy
